server:
  port: 50000
  sender_email: cae@cae.com
  user_stats: http://127.0.0.1:50001
  metadata: http://127.0.0.1:50002
  notification: http://127.0.0.1:50003

telemetry:
  tracing:
    enabled: true
    service_name: crm

auth:
  pk: |
    -----BEGIN PUBLIC KEY-----
    MCowBQYDK2VwAyEAfM+lwNHj6TRJ3EGP38lIJcOo9Dlt2u2JzcwWMbu7jQY=
    -----END PUBLIC KEY-----
