server:
  port: 50002

telemetry:
  tracing:
    enabled: true
    service_name: crm-metadata

auth:
  pk: |
    -----BEGIN PUBLIC KEY-----
    MCowBQYDK2VwAyEAfM+lwNHj6TRJ3EGP38lIJcOo9Dlt2u2JzcwWMbu7jQY=
    -----END PUBLIC KEY-----
