server:
  port: 50001
  db_url: http://localhost:18123
  db_name: crm
  db_type: clickhouse
  # db_url: postgres://postgres:postgres@localhost:5432
  # db_name: stats
  # db_type: postgres

telemetry:
  tracing:
    enabled: true
    service_name: user-stat

auth:
  pk: |
    -----BEGIN PUBLIC KEY-----
    MCowBQYDK2VwAyEAfM+lwNHj6TRJ3EGP38lIJcOo9Dlt2u2JzcwWMbu7jQY=
    -----END PUBLIC KEY-----
